'use strict';

module.exports = {
    host: process.env.HOST,
    ldap: process.env.LDAP_URL,
    tokenSecret: process.env.TOKEN_SECRET,
    tokenAlgo: process.env.TOKEN_ALGO,
    tokenExpires: process.env.TOKEN_EXPIRES,
    dbHost: process.env.DB_HOST,
    dbUser: process.env.DB_USER,
    dbPassword: process.env.DB_PASSWORD,
    dbName: process.env.DB_NAME,
    elasticSearch: process.env.ELASTIC_SEARCH,
    elasticSearchIndex: process.env.ELASTIC_SEARCH_INDEX,
    communityTnPath: process.env.COMMUNITY_TN_PATH,
    collectionTnPath: process.env.COLLECTION_TN_PATH,
    objectPath: process.env.OBJECT_PATH,
    importPath: process.env.IMPORT_PATH,
    tempPath: process.env.TEMP_PATH,
    apiUrl: process.env.API_URL,
    namespace: process.env.REPO_NAMESPACE,
    sftpHost: process.env.SFTP_HOST,
    sftpId: process.env.SFTP_ID,
    sftpPwd: process.env.SFTP_PWD,
    sftpRemotePath: process.env.SFTP_REMOTE_PATH,
    archivematicaApi: process.env.ARCHIVEMATICA_API,
    archivematicaUsername: process.env.ARCHIVEMATICA_USERNAME,
    archivematicaApiKey: process.env.ARCHIVEMATICA_API_KEY,
    archivematicaTransferSource: process.env.ARCHIVEMATICA_TRANSFER_SOURCE,
    duraCloudApi: process.env.DURACLOUD_API,
    duraCloudUser: process.env.DURACLOUD_USER,
    duraCloudPwd: process.env.DURACLOUD_PWD,
    errorTn: process.env.ERROR_TN,
    smtp: process.env.SMTP,
    fromEmail: process.env.FROM_EMAIL,
    emailSubject: process.env.SUBJECT
};