#!/bin/bash

# set env var - export API_KEY="<api-key>"

curl -X POST \
  'http://localhost:8000/api/admin/v1/repo/reset?api_key='<api-key> \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Postman-Token: 94fb2860-2340-4720-98c3-e5f8c1120e86' \
  -H 'cache-control: no-cache' \
  -d pid=d16407b5-9d48-414c-8fdc-8c35836483cf