#!/bin/bash

# set env var - export API_KEY="<api-key>"

curl -X POST \
  'http://localhost:8000/api/admin/v1/utils/objects/delete?api_key='${API_KEY} \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 184' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Host: localhost:8000' \
  -H 'cache-control: no-cache' \
  -d 'is_member_of_collection=<pid>&delete_reason=<reason>'