#!/bin/bash

# set env var - export API_KEY="<api-key>"

curl -X POST \
  'http://localhost:8000/api/admin/v1/indexer?api_key='${API_KEY} \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'cache-control: no-cache' \
  -d sip_uuid=34eca438-f881-47cf-aaf8-61afa3199725
