#!/bin/bash

# set env var - export API_KEY="<api-key>"

curl -X POST \
  'http://localhost:8000/api/admin/v1/repo/reset?api_key='${API_KEY} \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'cache-control: no-cache' \
  -d pid=<pid-here>