#!/bin/bash
curl -X PUT \
  'http://localhost:8000/api/admin/v1/repo/object?api_key=M7dHS21r47RsgyxSd7XJaEAgf7Miha01' \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'Host: localhost:8000' \
  -H 'User-Agent: PostmanRuntime/7.17.1' \
  -H 'cache-control: no-cache'